---
application:
  name: "testnodejsapi"
  project: "testNodeJsAPI1234"
  organization: "QoveryCommunity"
routers:
- name: "main-testnodejsapi"
  routes:
  - application_name: "testnodejsapi"
    paths:
    - "/*"
